package gui;

import java.awt.Color;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.LineBorder;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import dao.SanPhamDAO;
import entities.SanPham;


public class FormDanhSachSanPhamBanChay extends javax.swing.JFrame {
    private List<SanPham> listSanPham;

    public FormDanhSachSanPhamBanChay(List<SanPham>listSanPham) {
        this.listSanPham = listSanPham;
        initComponents();
        designTable();
        tblDanhSachBanChay();
    }

     private void designTable() {
        tbl_danhSachSanPham.getTableHeader().setFont(new java.awt.Font("Arial", 0, 12));
        tbl_danhSachSanPham.getTableHeader().setOpaque(false);
        tbl_danhSachSanPham.getTableHeader().setBackground(new Color(144, 238, 144));
        tbl_danhSachSanPham.getTableHeader().setForeground(Color.WHITE);
        tbl_danhSachSanPham.setDefaultEditor(Object.class, null); // Không cho phép edit
        tbl_danhSachSanPham.setRowHeight(30);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        lbl_1.setBounds(299, 14, 471, 49);
        scr_1 = new javax.swing.JScrollPane();
        scr_1.setBounds(13, 69, 1100, 325);
        tbl_danhSachSanPham = new javax.swing.JTable();
        lbl_2 = new javax.swing.JLabel();
        lbl_2.setBounds(1092, 3, 31, 32);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        lbl_1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("TOP 10 SẢN PHẨM BÁN CHẠY");
        lbl_1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tbl_danhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Top", "Mã sản phẩm", "Tên sản phẩm", "Số lượng đã bán", "Phân loại", "Màu sắc", "Kích cỡ", "Giá bán"
            }
        ));
        scr_1.setViewportView(tbl_danhSachSanPham);

        lbl_2.setText("    X");
        lbl_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(container, GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(container, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        container.setLayout(null);
        container.add(lbl_1);
        container.add(lbl_2);
        container.add(scr_1);
        
        btnXuatFile = new JButton("Xuất File");
        btnXuatFile.setFont(new Font("Arial", Font.BOLD, 13));
        btnXuatFile.setBackground(new Color(255, 255, 255));
        btnXuatFile.setBorder(new LineBorder(new Color(0, 0, 0), 2));
        btnXuatFile.setBounds(494, 432, 117, 49);
        container.add(btnXuatFile);
        getContentPane().setLayout(layout);
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void btnXuatFileActionPerformed(ActionEvent evt) {
    	exportToPDF();
		// TODO Auto-generated method stub
    	
	}

	private void exportToPDF() {
		// TODO Auto-generated method stub
		JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file");

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            Document document = new Document();
        try {
        	PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileToSave.getAbsolutePath() + ".pdf"));
            document.open();
            BaseFont baseFont = BaseFont.createFont("c:/windows/fonts/arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            com.itextpdf.text.Font font = new com.itextpdf.text.Font(baseFont, 12);

            // Open the document for writing
            document.open();

            // Add a title to the document
            Paragraph title = new Paragraph("TOP 10 SẢN PHẨM BÁN CHẠY", font);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Add the table to the document
            PdfPTable table = new PdfPTable(tbl_danhSachSanPham.getColumnCount());
            for (int i = 0; i < tbl_danhSachSanPham.getColumnCount(); i++) {
                table.addCell(new Phrase(tbl_danhSachSanPham.getColumnName(i), font));
            }

            for (int i = 0; i < tbl_danhSachSanPham.getRowCount(); i++) {
                for (int j = 0; j < tbl_danhSachSanPham.getColumnCount(); j++) {
                    table.addCell(new Phrase(tbl_danhSachSanPham.getValueAt(i, j).toString(), font));
                }
            }

            document.add(table);
            Paragraph printDateTime = new Paragraph("Ngày giờ in: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()), font);
            printDateTime.setAlignment(Element.ALIGN_LEFT);
            document.add(printDateTime);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Close the document
            if (document != null && document.isOpen()) {
                document.close();
            	}
        	}
        	JOptionPane.showMessageDialog(this, "Báo cáo đã được xuất ra file PDF.");
        }       
	}

	private void lbl_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lbl_2MouseClicked

    private void tblDanhSachBanChay(){
        DefaultTableModel dtm = (DefaultTableModel) tbl_danhSachSanPham.getModel();
        dtm.setRowCount(0);
        for(int i = 0; i < listSanPham.size(); i++){
            SanPham sp = listSanPham.get(i);
            Object[] rowData = {i+1, sp.getMaSP(), sp.getTenSP(), sp.getSoLuong(), sp.getPhanLoai().getPhanLoai(), sp.getMauSac().getMauSac(),
            sp.getKichThuoc().getKichThuoc(), NumberFormat.getInstance().format(sp.getGiaBan())};
            dtm.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JScrollPane scr_1;
    private javax.swing.JTable tbl_danhSachSanPham;
    private JButton btnXuatFile;
}
